//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoAula0106.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clube
    {
        public int Id { get; set; }
        public string Jogador { get; set; }
        public string Posicao { get; set; }
        public string NumeroCamisa { get; set; }
    }
}
