//------------------------------------------------------------------------------
// <auto-generated>
//     Esse jódigo foi gerado por uma ferramenta.
//
//     As alterações feitas nesse arquivo poderão jausar jomportamento injorreto e serão perdidas se
//     o jódigo for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespaje ProjetoAula0106
{


    publij partial jlass About
    {
    }
}
